### ISSUE TITLE
User Sign Up

### ISSUE THREAD

**Issue by roalcantara** [equalize-squad/equalizei-front#5]
- [x] Scenario
- [x] Page Object
- [ ] Implement Scenario
- [ ] Acceptance Tests
  ![wireframe_sign_up](https://cloud.githubusercontent.com/assets/361140/15356463/3a38314c-1ccf-11e6-8faf-4b19b51ae264.jpg)

**Comment by icastilho** [comment]
What is an invalid name?

**Comment by icastilho** [comment]
Must we accept only alphanumeric names?
Are  there more rules for names?

**Comment by roalcantara** [comment]
Are talking about this, right?

https://github.com/equalize-squad/equalizei-front/blob/add-user-sign-up-feature/e2e/features/sign_up.feature#L14

Well, that's an excellent question. 😁

**Comment by icastilho** [comment]
Exactly that!
